### PR TITLE
Allow Spree 1.3.x use

### PR DESCRIPTION
**Pull request by JDutil**

### CODE REVIEW

**Comment by christoph-buente** [comment]
+1

**Comment by pickledolives** [comment]
+1

**Comment by JDutil** [comment]
@radar could you take a look at this and the other PRs for the repo when you get a chance please.  I don't have commit access to this repo like the other extensions.  Perhaps @schof could add this repo and other extensions to the organizations team I'm on so that more of us would be able to help keep this up to date.

**Comment by BDQ** [comment]
@jdutil you should have commit access now, thanks for all the great work.

**Comment by JDutil** [comment]
Thanks @BDQ

**Pull request merged**
