### PR TITLE
Fixed "superclass mismatch for class Promotion" error.

### PR DESCRIPTION
**Pull request by zubin**
See my commit message for details. There's probably a better way to fix it, but for me this was better than no fix.

### CODE REVIEW

**Comment by radar** [comment]
I think the way to fix this would just be to have `class Promotion` always inherit from `Spree::Activator`, since that will always be around because it is within core. Is there any reason not to do that here?

**Comment by zubin** [comment]
Ryan, I'm not sure I follow because your commit does what you've suggested:

```
class Promotion < Spree::Activator
```

... and `Promotion` isn't defined anywhere else (I've looked through all
the gems in our app).

Am I missing something?

## 

Zubin

**Comment by radar** [comment]
Sorry, I was wrong. Your patch is correct.

**Comment by radar** [comment]
This has been merged to master and 1-3-stable now. Thanks Zubin :)

**Comment by zubin** [comment]
Actually this "fix" has broken promotion admin.

After adding a promotion, editing it causes this error which is raised from spree_product_groups's override (difficult to tell from the trace).

```
ActionView::Template::Error (undefined method `product_group' for #<Spree::Promotion::Rules::Product:0x007fbdfb0f7510>):
    1:
    2: <p class="field products_rule_products_source_field">
    3:   <label><%= radio_button_tag "#{param_prefix}[products_source]", :manual, promotion_rule.product_group.nil? %> <%= t "product_rule.product_source.manual" %></label>
    4:   <label><%= radio_button_tag "#{param_prefix}[products_source]", :group, promotion_rule.product_group.present? %> <%= t('product_rule.product_source.group') %></label>
    5: </p>
    6: <p class="field products_rule_product_group">
  activemodel (3.2.12) lib/active_model/attribute_methods.rb:407:in `method_missing'
  activerecord (3.2.12) lib/active_record/attribute_methods.rb:149:in `method_missing'
  spree_promo (1.3.2) app/views/spree/admin/promotions/rules/_product.html.erb:3:in `_589bb2ddbe9b7e438cf0e00cbe44535f'
```

Unfortunately I don't have a solution at this point.

**Comment by radar** [comment]
@zubin:

I wasn't able to reproduce this issue by creating a blank promotion in the admin backend. It was only when I attempted to add a product rule did this issue occur, and my stacktrace matches yours. Looking into why this is happening.

**Comment by radar** [comment]
Fixed with @b5d85b51d2da47c09273331f6f1706176253b71f. There's no more error that will come up when you choose the "Product" rule any more. Relatively simple fix.

**Comment by zubin** [comment]
Nice one Ryan! I hope that's fixed it, however I'm a little dubious because
your fix is the reverse of the previous logic!

## 

Zubin

**Comment by radar** [comment]
Well, the whole point of that if statement is to _not_ run the code if `Spree::Promotion` is defined. If `Spree::Promotion` is not defined, then that whole override will fall over because it'll be referencing classes that don't exist.

Make sense?

**Comment by zubin** [comment]
I'm confused. Isn't that code only relevant if spree_promotions gem is
present/loaded?

## 

Zubin

**Comment by radar** [comment]
Oops yeah. Got my sentences mixed. Point is: if statement is right way of doing this.

**Comment by zubin** [comment]
Ok, I hope it works. I was trying to say the previous attempt to fix it, which partially worked, did the reverse. From memory, an error was raised anytime an (unrelated) exception was raised. So although this resolves the error you found, it probably doesn't resolve other errors. We're no longer using spree_groups so I can't confirm this just now.

**Pull request closed without merging**
