### PR TITLE
Respecting new Spree localization practices + resolving issue #28

### LINKED ISSUE #28: Spree 2.1 - Error when trying to access Products Groups in admin
On a fresh install of Spree 2.1 getting the following error when trying to access Product Groups in admin:

undefined method `relation' for #ActiveRecord::Relation::ActiveRecord_Relation_Spree_Product:0x007fdabb387f00

### PR DESCRIPTION
**Pull request by GarPit**
"Product.method(self.name.intern).arity == 0" will not work for "ascend_by_updated_at" and other sorts cause it returns -1. This is because such scopes (added as simple scopes) were added via "scope" method, not like other scopes that were defined via "define_method". So this request should fix #28.

I saw a lot of "t()" helper was used in partials. This request also updated all views with "Spree.t" helper using. It adds correct translations too.

### CODE REVIEW

**Comment by radar** [comment]
This PR does not apply cleanly on the master branch when I try to apply it using this command:

```
hub am -3 https://github.com/spree/spree_product_groups/pull/31
```

Could you please clean this up and resubmit it?

**Comment by GarPit** [comment]
Yes, I guess the problem is that I made some merges and its including your commits that already in master.

**Comment by GarPit** [comment]
Should I reject your commits from this PR?

**Comment by radar** [comment]
Yes please

**Comment by priyank-gupta** [comment]
@radar, when will 27645d88be2bf12a4e7edf88f24d8991a4e89d37 commit by @GarPit be merged in branch 2-1-stable ?

As it has fix for "app/models/spree/product_scope.rb" model.

Thanks.

**Pull request closed without merging**
